version: "3.8"

services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka_instance
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka_data:/var/lib/kafka/data

  verification_service_db:
    image: postgres:16
    container_name: verification_service_db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: verification_service
      POSTGRES_PASSWORD: 12345678
      POSTGRES_USER: postgres
    ports:
      - "5433:5432"
    volumes:
      - verification_data:/var/lib/postgresql/data

  issuance_service_db:
    image: postgres:16
    container_name: issuance_service_db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: issuance_service
      POSTGRES_PASSWORD: 12345678
      POSTGRES_USER: postgres
    ports:
      - "5434:5432"
    volumes:
      - issuance_data:/var/lib/postgresql/data

volumes:
  kafka_data:
  verification_data:
  issuance_data:
